name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
            arch: x64
            flags: -D ANDROID_STL=c++_shared -D ANDROID_PLATFORM=android-35
          - os: ubuntu-latest
            platform: android
            arch: ia32
            flags: -D ANDROID_STL=c++_shared -D ANDROID_PLATFORM=android-35
          - os: ubuntu-latest
            platform: android
            arch: arm64
            flags: -D ANDROID_STL=c++_shared -D ANDROID_PLATFORM=android-35
          - os: ubuntu-latest
            platform: android
            arch: arm
            flags: -D ANDROID_STL=c++_shared -D ANDROID_PLATFORM=android-35
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: choco upgrade llvm
        if: ${{ matrix.platform == 'win32' }}
      - run: npm install -g bare-runtime bare-make
      - run: npm install
      - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --debug ${{ matrix.flags }}
      - run: bare-make build
